weather:
   path: /weather/{city}/{country}
   controller: App\Controller\WeatherController::cityAction

crud:
   path: /weather/crud
   controller: App\Controller\WeatherController::crud

app_logout:
   path: /logout
   methods: GET